<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <PackageId>ViShap.Viper</PackageId>
        <Authors>Vahe Babayan (0xVahe)</Authors>
        <Company>ViShap Solutions</Company>
        <Copyright>Copyright © ViShap Solutions 2026</Copyright>
        <Description>Ultimate binary engineering solutions ecosystem.</Description>
        <RepositoryUrl>https://github.com/ViShap-Solutions/Viper</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>METAPACK-README.md</PackageReadmeFile>
        <IsPackable>true</IsPackable>
        <Title>Viper</Title>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ViShap.Viper.Core\ViShap.Viper.Core.csproj" />
        <ProjectReference Include="..\ViShap.Viper.Serialization\ViShap.Viper.Serialization.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
        <None Include="METAPACK-README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
    
</Project>
